import {cleanMotifs} from './motif-model.js';
import {journey} from './journey.js';
import {stageMarkup,bindStage} from './stages.js';
import {Garden,INKS} from './garden.js';
import {copy,journeyCopy,printCopy} from './content.js';
const app=document.querySelector('#app');
const reduced=matchMedia('(prefers-reduced-motion: reduce)');
const saved=(()=>{try{return JSON.parse(localStorage.getItem('salon-jardin')||'{}')}catch{return {}}})();
const state={motifs:cleanMotifs(saved.motifs),edited:!!saved.edited,bloom:!!saved.bloom,repeated:!!saved.repeated,palette:Number.isInteger(saved.palette)&&saved.palette>=0&&saved.palette<INKS.length?saved.palette:0,spacing:Number.isFinite(saved.spacing)?Math.max(0,Math.min(100,saved.spacing)):45,ground:[0,1,2].includes(saved.ground)?saved.ground:0,layout:saved.layout===0?0:1,scale:saved.scale===1?1:0,thought:[0,1,2].includes(saved.thought)?saved.thought:null,answer:[0,1].includes(saved.answer)?saved.answer:null,lastCreator:[0,1,2,3].includes(saved.lastCreator)?saved.lastCreator:1,beforeDesign:saved.beforeDesign||null,activeCreator:null,explored:Array.isArray(saved.explored)?saved.explored:[false,false,false,false],person:saved.person==='julie'?'julie':'sonia',paused:reduced.matches,sound:false};
let garden,locale='fr',scene='jardin',phase=0,audio,oscillators=[],master,routeTimer;
const arrow='<svg class="arrow" viewBox="0 0 30 20" fill="none" aria-hidden="true"><path d="M1 10h26M19 2l8 8-8 8" stroke="currentColor" stroke-width="1.3"/></svg>';
const flower='<svg viewBox="0 0 32 32" fill="currentColor" aria-hidden="true"><path d="M16 14C-1-8-6 20 13 16C-8 32 22 41 16 19C35 40 44 11 20 16C41-2 10-9 16 14Z"/></svg>';
function icon(kind){return `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${kind==='pause'?'<path d="M9 5v14M15 5v14"/>':kind==='play'?'<path d="m8 4 12 8-12 8z"/>':kind==='sound'?'<path d="M4 9h4l5-4v14l-5-4H4zM17 8a6 6 0 0 1 0 8m3-11a10 10 0 0 1 0 14"/>':'<path d="M4 9h4l5-4v14l-5-4H4zM17 9l5 6m0-6-5 6"/>'}</svg>`;}
function save(){try{localStorage.setItem('salon-jardin',JSON.stringify({motifs:state.motifs,edited:state.edited,bloom:state.bloom,repeated:state.repeated,palette:state.palette,spacing:state.spacing,person:state.person,ground:state.ground,layout:state.layout,scale:state.scale,thought:state.thought,answer:state.answer,explored:state.explored,lastCreator:state.lastCreator,beforeDesign:state.beforeDesign}))}catch{}}
function url(page,lang=locale,step=0){return `#/${lang}/${page}${['fleur','creatrices'].includes(page)?'/'+step:''}`;}
function header(t){return `<header class="masthead"><a class="brand" href="${url('jardin')}" aria-label="${t.home}"><span class="brand-mark">${flower}</span><span>salon<b>format</b></span></a><span class="mast-title">Un jardin à soi</span><div class="utilities"><div class="utility-group"><button class="icon-button" id="sound" aria-label="${state.sound?t.soundOn:t.soundOff}" aria-pressed="${state.sound}" title="${state.sound?t.soundOn:t.soundOff}">${icon(state.sound?'sound':'mute')}</button><button class="icon-button" id="motion" aria-label="${state.paused?t.play:t.pause}" aria-pressed="${state.paused}" title="${state.paused?t.play:t.pause}">${icon(state.paused?'play':'pause')}</button></div><nav class="languages" aria-label="${t.language}">${['fr','de','en'].map(l=>`<button lang="${l}" data-language="${l}" aria-label="${{fr:'Français',de:'Deutsch',en:'English'}[l]}" aria-pressed="${l===locale}">${l.toUpperCase()}</button>`).join('')}</nav></div></header>`;}
function footer(t){const j=journey[locale],pages=['jardin','atelier','souvenir'],active=scene==='decouverte'?'jardin':['creatrices','retour','choix','fleur'].includes(scene)?'atelier':scene;return `<footer class="page-footer full-journey"><span class="signature"><span class="tiny-flower">${flower}</span><span>${t.credit}</span></span><nav class="journey" aria-label="${j.duration}">${pages.map((p,i)=>`<a href="${url(p)}" ${active===p?'aria-current="step"':''}><i></i><span>${({fr:['Le jardin','Mon tissu','À emporter'],de:['Der Garten','Mein Stoff','Zum Mitnehmen'],en:['The garden','My fabric','Take it home']})[locale][i]}</span></a>`).join('')}</nav><span class="prototype-label">${j.duration}</span></footer>`;}
function render(focus=false){garden?.destroy();if(scene==='creatrices'){if(state.activeCreator!==phase){state.beforeDesign={palette:state.palette,ground:state.ground,layout:state.layout,scale:state.scale};state.activeCreator=phase;state.lastCreator=phase;save();}}else state.activeCreator=null;const t=copy[locale];document.documentElement.lang=locale;document.body.classList.toggle('paused',state.paused);document.querySelector('.skip-link').textContent=t.skip;document.title='Un jardin à soi — Salon Format';
  if(scene==='jardin'){
    app.innerHTML=`<div class="shell cover-shell">${header(t)}<main id="main" class="hero scene-enter"><canvas class="garden-cover" aria-hidden="true"></canvas><div class="hero-copy"><h1 tabindex="-1"><span>${t.title[0]}</span><span>${t.title[1]}</span></h1><p class="hero-intro">${t.intro}</p><a class="enter" href="${url('atelier')}">${t.enter}${arrow}</a><p class="hero-hint">${journeyCopy[locale].hint}</p><p class="print-intro">${journey[locale].duration}</p></div></main>${footer(t)}</div>`;
  }else if(scene==='fleur'){
    const p={...printCopy[locale],actions:[...printCopy[locale].actions.slice(0,2),journey[locale].printNext]};
    app.innerHTML=`<div class="shell print-shell">${header(t)}<main id="main"><section class="print-scene scene-enter" aria-labelledby="print-title" data-phase="${phase}"><div class="print-top"><nav class="print-steps" aria-label="${{fr:"Les étapes d’impression",de:"Die Druckschritte",en:"Printing steps"}[locale]}">${p.steps.map((label,i)=>`<a href="${url('fleur',locale,i)}" ${i===phase?'aria-current="step"':''}><span>${i+1}</span>${label}</a>`).join('')}</nav><h1 id="print-title" tabindex="-1">${p.titles[phase]}</h1><p id="print-help">${p.help[phase]}</p></div><div class="print-art"><canvas aria-hidden="true"></canvas><button class="print-target" ${phase===2?'hidden':''} aria-label="${phase===0?p.printLabel:p.repeatLabel}"></button><div class="material-caption" aria-hidden="true"><span id="material">${p.material[phase]}</span><svg viewBox="0 0 80 45" fill="none"><path d="M2 2C14 27 40 34 73 24m-9-8 10 8-11 9" stroke="currentColor" stroke-width="1.2"/></svg></div></div><div class="print-bottom"><div class="ink-controls" ${phase!==0?'hidden':''}><span>${p.ink}</span><div class="inks" role="group" aria-label="${p.ink}">${INKS.map((colour,i)=>`<button class="ink" data-ink="${i}" aria-label="${p.inkNames[i]}" aria-pressed="${state.palette===i}"><span style="--swatch:${colour}"></span><b>${p.inkNames[i]}</b></button>`).join('')}</div></div><button class="print-action" id="print-action">${p.actions[phase]}${arrow}</button><p class="process-note" id="process-note">${p.notes[phase]}</p><div class="print-links"><a id="print-back" href="${phase===0?url('atelier'):url('fleur',locale,phase-1)}">${arrow}${p.back}</a><a href="${url('fleur',locale,0)}" ${phase===0?'hidden':''}>${p.again}</a></div></div></section></main>${footer(t)}<div class="sr-only" id="status" role="status"></div></div>`;
  }
  if(!['jardin','fleur'].includes(scene)){app.innerHTML=`<div class="shell extended-shell ${scene}-shell">${header(t)}${stageMarkup(scene,phase,locale,state,url,arrow)}${footer(t)}</div>`;garden=bindStage(scene,phase,locale,state,save);}else garden=new Garden(document.querySelector('canvas'),{scene,paused:state.paused,bloom:scene==='fleur'&&phase>0?1:0,repeated:scene==='fleur'&&phase===2,palette:state.palette,spacing:state.spacing});
  bind();if(focus)document.querySelector('h1').focus({preventScroll:true});
}
function updatePrint(){
 const p={...printCopy[locale],actions:[...printCopy[locale].actions.slice(0,2),journey[locale].printNext]}; garden.set({bloom:phase>0?1:0,repeated:phase===2});
 document.querySelector('.print-scene').dataset.phase=phase;
 document.querySelector('#print-title').textContent=p.titles[phase];
 document.querySelector('#print-help').textContent=p.help[phase];
 document.querySelector('#material').textContent=p.material[phase];
 document.querySelector('#process-note').textContent=p.notes[phase];
 document.querySelector('#print-action').innerHTML=p.actions[phase]+arrow;
 document.querySelector('.ink-controls').hidden=phase!==0;
 document.querySelector('.print-target').hidden=phase===2;
 document.querySelector('.print-target').setAttribute('aria-label',phase===0?p.printLabel:p.repeatLabel);
 document.querySelector('#print-back').href=phase===0?url('atelier'):url('fleur',locale,phase-1);
 document.querySelector('.print-links a:last-child').hidden=phase===0;
 document.querySelectorAll('.print-steps a').forEach((a,i)=>{if(i===phase)a.setAttribute('aria-current','step');else a.removeAttribute('aria-current');});
 document.querySelector('#status').textContent=phase===1?p.printed:phase===2?p.repeated:'';
 state.bloom=phase>0;state.repeated=phase===2;save();chime();
}
function advancePrint(){location.hash=phase<2?url('fleur',locale,phase+1):url('atelier');}
function bind(){
  document.querySelectorAll('[data-language]').forEach(b=>b.addEventListener('click',()=>{locale=b.dataset.language;history.replaceState(null,'',url(scene,locale,phase));render(false);}));
  document.querySelector('#motion').addEventListener('click',()=>{state.paused=!state.paused;document.body.classList.toggle('paused',state.paused);garden.set({paused:state.paused});const b=document.querySelector('#motion'),t=copy[locale];b.innerHTML=icon(state.paused?'play':'pause');b.setAttribute('aria-pressed',state.paused);b.setAttribute('aria-label',state.paused?t.play:t.pause);b.title=state.paused?t.play:t.pause;});
  document.querySelector('#sound').addEventListener('click',toggleSound);
  if(scene==='fleur'){
    document.querySelector('.print-target').addEventListener('click',advancePrint);
    document.querySelector('#print-action').addEventListener('click',advancePrint);
    document.querySelectorAll('[data-ink]').forEach(b=>b.addEventListener('click',()=>{state.palette=Number(b.dataset.ink);document.querySelectorAll('[data-ink]').forEach(s=>s.setAttribute('aria-pressed',Number(s.dataset.ink)===state.palette));garden.set({palette:state.palette});save();chime();}));
    document.querySelectorAll('[data-person]').forEach(b=>b.addEventListener('click',()=>{state.person=b.dataset.person;const t=copy[locale];document.querySelectorAll('[data-person]').forEach(p=>p.setAttribute('aria-pressed',p.dataset.person===state.person));document.querySelector('#person-content').innerHTML=`<p class="person-role">${t[state.person+'Role']}</p><p class="person-text">${t[state.person]}</p>`;save();}));
  }
}
function readRoute(){const match=location.hash.match(/^#\/(fr|de|en)\/(jardin|decouverte|fleur|tissu|choix|creatrices|retour|atelier|souvenir)(?:\/([0-3]))?$/);if(match){locale=match[1];scene=match[2];phase=Math.min(Number(match[3]||0),scene==='creatrices'?3:scene==='fleur'?2:0);}else{locale=['fr','de','en'].includes(new URLSearchParams(location.search).get('lang'))?new URLSearchParams(location.search).get('lang'):'fr';scene='jardin';phase=0;history.replaceState(null,'',url(scene));}}
function changeRoute(){clearTimeout(routeTimer);const oldScene=scene,oldLocale=locale;readRoute();if(scene==='fleur'&&oldScene===scene&&oldLocale===locale&&document.querySelector('.print-scene')){updatePrint();return;}if(state.paused){render(true);window.scrollTo(0,0);return;}document.querySelector('main')?.classList.add('camera-depart');let veil=document.createElement('div');veil.className='transition-veil wipe';document.body.append(veil);routeTimer=setTimeout(()=>{render(true);window.scrollTo(0,0);},250);setTimeout(()=>veil.remove(),740);}
window.addEventListener('hashchange',changeRoute);reduced.addEventListener('change',e=>{state.paused=e.matches;render(false);});
async function toggleSound(){try{if(!audio){audio=new (window.AudioContext||window.webkitAudioContext)();master=audio.createGain();master.gain.value=0;master.connect(audio.destination);[130.81,196,261.63].forEach((f,i)=>{const o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.value=f;g.gain.value=.055/(i+1);o.connect(g);g.connect(master);o.start();oscillators.push(o);});}state.sound=!state.sound;if(state.sound){await audio.resume();master.gain.setTargetAtTime(.65,audio.currentTime,.4);}else{master.gain.setTargetAtTime(0,audio.currentTime,.2);}const t=copy[locale],b=document.querySelector('#sound');b.innerHTML=icon(state.sound?'sound':'mute');b.setAttribute('aria-label',state.sound?t.soundOn:t.soundOff);b.title=state.sound?t.soundOn:t.soundOff;b.setAttribute('aria-pressed',state.sound);}catch{state.sound=false;}}
function chime(){if(!audio||!state.sound)return;let o=audio.createOscillator(),g=audio.createGain();o.frequency.value=[523.25,659.25,783.99][state.palette%3];o.connect(g);g.connect(master);g.gain.setValueAtTime(0,audio.currentTime);g.gain.linearRampToValueAtTime(.08,audio.currentTime+.025);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+1.4);o.start();o.stop(audio.currentTime+1.5);}
document.addEventListener('visibilitychange',()=>{if(audio){if(document.hidden)audio.suspend();else if(state.sound)audio.resume();}});
document.querySelector('.skip-link').addEventListener('click',e=>{e.preventDefault();const main=document.querySelector('#main');main.tabIndex=-1;main.focus();main.scrollIntoView({behavior:'instant'});});
readRoute();render();
