import {makeTile} from './textile.js?v=popova-and-patterns';
const copy={
 de:{label:'Beispiel mit eigenen Motiven von Salon Format, kein Werk der Gestalterin.',title:['Eine Blume fällt auf','Die Blume bleibt gleich','Ein Dreieck, zwei Muster','Wie viel Platz bekommt die Blume?'],change:['Eine Blume umfärben','Gelben Hintergrund ansehen','Reihen versetzen','Blumen vergrößern'],back:['Alle Blumen wieder lila färben','Hellen Hintergrund ansehen','Reihen wieder ausrichten','Blumen verkleinern'],before:['Alle Blumen sind lila. Färbe eine davon orange und schau, wohin du zuerst blickst.','Diese Blume ist lila. Wechsle den Hintergrund von Hell zu Gelb und vergleiche, wie die Farbe wirkt.','Hier stehen die Dreiecke genau untereinander. Verschiebe jede zweite Reihe ein Stück nach rechts.','Zwischen den kleinen Blumen ist viel Stoff zu sehen. Vergrößere die Blumen und vergleiche die beiden Muster.'],after:['Jetzt ist eine Blume orange. Du kannst einzelne Stellen im Muster hervorheben, ohne die Form zu ändern.','Die Blume hat genau dieselbe Farbe wie vorher. Nur der Hintergrund ist jetzt gelb. Wirkt das Lila für dich gleich?','Die mittlere Reihe ist nach rechts verschoben. Ihre Dreiecke stehen jetzt zwischen denen der oberen und unteren Reihe.','Jetzt füllen die Blumen fast die ganze Fläche. Auch die freien Stellen dazwischen haben ihre Form verändert.']},
 fr:{label:'Exemple avec des motifs de Salon Format, pas une œuvre de la créatrice.',title:['Une fleur attire le regard','La fleur reste la même','Un triangle, deux motifs','Quelle place donner à la fleur ?'],change:['Changer la couleur d’une fleur','Voir le fond jaune','Décaler les rangées','Agrandir les fleurs'],back:['Remettre toutes les fleurs en violet','Revoir le fond clair','Réaligner les rangées','Réduire les fleurs'],before:['Toutes les fleurs sont violettes. Passez-en une en orange et regardez celle que vous remarquez en premier.','Cette fleur est violette. Passez du fond clair au fond jaune et comparez son apparence.','Les triangles sont alignés les uns sous les autres. Décalez une rangée sur deux vers la droite.','On voit beaucoup de tissu entre les petites fleurs. Agrandissez-les et comparez les deux motifs.'],after:['Une fleur est maintenant orange. On peut attirer le regard sur un endroit du motif sans changer les formes.','La fleur a exactement la même couleur. Seul le fond est devenu jaune. Le violet vous semble-t-il identique ?','Les triangles sont maintenant en quinconce. La forme et la couleur sont les mêmes, mais le motif a changé.','Les fleurs remplissent presque toute la surface. Les espaces entre elles ont aussi changé de forme.']},
 en:{label:'An example using Salon Format motifs, not an artwork by the designer.',title:['One flower stands out','The flower stays the same','One triangle, two patterns','How much space does a flower get?'],change:['Change one flower’s colour','Try a yellow background','Offset the rows','Make the flowers bigger'],back:['Make all the flowers purple again','Return to the pale background','Line up the rows again','Make the flowers smaller'],before:['All the flowers are purple. Turn one orange and notice where you look first.','This flower is purple. Switch from the pale background to yellow and compare how it looks.','The triangles line up directly below each other. Move every second row a little to the right.','There is plenty of fabric between the small flowers. Make them bigger and compare the two patterns.'],after:['One flower is now orange. You can draw attention to part of a pattern without changing its shapes.','The flower is exactly the same colour as before. Only the background is now yellow. Does the purple look the same to you?','The triangles now sit in the gaps between those in the next row. The shape and colour are unchanged, but you have a second pattern.','The flowers now fill almost the whole surface. The spaces between them have changed shape too.']}
};
export function demoMarkup(locale,phase){const c=copy[locale];return `<section class="idea-demo" data-phase="${phase}" data-locale="${locale}"><h3>${c.title[phase]}</h3><canvas width="600" height="260" role="img" aria-label="${c.before[phase]}"></canvas><button type="button" id="idea-change">${c.change[phase]}</button><p id="idea-observation" aria-live="polite">${c.before[phase]}</p><small>${c.label}</small></section>`;}
export function bindDemo(){const root=document.querySelector('.idea-demo'),phase=Number(root.dataset.phase),c=copy[root.dataset.locale],canvas=root.querySelector('canvas'),ctx=canvas.getContext('2d'),button=root.querySelector('button'),note=root.querySelector('#idea-observation');let changed=false;
 function paint(){const motifs=Array.from({length:phase===1?1:12},(_,i)=>({x:phase===1?.5:.125+(i%4)*.25+(phase===2&&changed&&Math.floor(i/4)%2?.125:0),y:phase===1?.215:.075+Math.floor(i/4)*.14,size:phase===1?.095:phase===3?(changed?.12:.035):.045,kind:phase===2?4:1,angle:0,ink:phase===0&&changed&&i===5?0:5}));ctx.drawImage(makeTile({ground:phase===1&&changed?2:0,motifs}),0,0);button.textContent=(changed?c.back:c.change)[phase];note.textContent=(changed?c.after:c.before)[phase];canvas.setAttribute('aria-label',note.textContent);}
 button.onclick=()=>{changed=!changed;paint()};paint();return {set(){},destroy(){button.onclick=null}};
}
