import {makeTile} from './textile.js?v=fresh-cloth-fit-screen';
const copy={
 de:{label:'Eigene Demonstration mit Salon-Format-Motiven, keine Werkabbildung.',title:['Farben kombinieren','Dieselbe Blume, anderer Hintergrund','Abstände verändern','Eine Form größer machen'],change:['Andere Farbkombination','Hintergrund wechseln','Abstände wechseln','Größe wechseln'],notes:['Nur die Farben wechseln. Form und Anordnung bleiben gleich.','Die Blume behält ihre Farbe. Wirkt sie auf dem anderen Hintergrund anders?','Dasselbe Motiv wird wiederholt. Die Abstände verändern den Rhythmus.','Die Form bleibt gleich. Wenn sie größer wird, nimmt sie mehr Raum ein.']},
 fr:{label:'Démonstration avec des motifs de Salon Format, sans reproduction d’œuvre.',title:['Associer les couleurs','Même fleur, autre fond','Changer les espaces','Agrandir une forme'],change:['Changer les couleurs','Changer le fond','Changer les espaces','Changer la taille'],notes:['Seules les couleurs changent. Les formes restent à la même place.','La fleur garde sa couleur. Semble-t-elle différente sur un autre fond ?','Le même motif se répète. Les espaces changent le rythme.','La forme reste la même. En grandissant, elle prend plus de place.']},
 en:{label:'A demonstration using Salon Format motifs, not a reproduction of an artwork.',title:['Combine colours','Same flower, different background','Change the spacing','Enlarge a shape'],change:['Change the colours','Change the background','Change the spacing','Change the size'],notes:['Only the colours change. The shapes and their positions stay the same.','The flower keeps its colour. Does it look different on another background?','The same motif repeats. The spacing changes the rhythm.','The shape stays the same. As it grows, it takes up more space.']}
};
export function demoMarkup(locale,phase){const c=copy[locale];return `<section class="idea-demo" data-phase="${phase}"><h3>${c.title[phase]}</h3><canvas width="600" height="260" role="img" aria-label="${c.notes[phase]}"></canvas><button type="button" id="idea-change" aria-pressed="false">${c.change[phase]}</button><p>${c.notes[phase]}</p><small>${c.label}</small></section>`;}
export function bindDemo(){const root=document.querySelector('.idea-demo'),phase=Number(root.dataset.phase),canvas=root.querySelector('canvas'),ctx=canvas.getContext('2d'),button=root.querySelector('button');let changed=false;
 function paint(){const motifs=Array.from({length:phase===2?6:phase===0?3:1},(_,i)=>({x:phase===2?.15+(i%3)*(changed?.34:.2):phase===0?.22+i*.28:.5,y:phase===2?.12+Math.floor(i/3)*(changed?.24:.13):.19,size:phase===3?(changed?.17:.08):.065,kind:1,angle:0,ink:phase===0?(changed?[2,6,5]:[5,0,2])[i]:5}));ctx.drawImage(makeTile({ground:phase===1&&changed?2:0,motifs}),0,0);button.setAttribute('aria-pressed',String(changed));}
 button.onclick=()=>{changed=!changed;paint()};paint();return {set(){},destroy(){button.onclick=null}};
}
