import {makeTile} from './textile.js?v=blank-white-cloth';
import {drawMotif,painterFor} from './motif-model.js?v=popova-and-patterns';
import {printCopy} from './content.js?v=fresh-cloth-fit-screen';
const words={de:{title:'Drucke deine erste Blume.',resume:'Drucke weitere Blumen auf deinen Stoff.',help:'Zieh den Druckstock auf den Stoff. Oder tippe auf die Stelle, an der die Blume stehen soll.',ink:'Druckfarbe',block:'Druckstock',context:'Blumen schmücken Stoffe schon seit Jahrhunderten. Schau dir an, wie sie in diesen Seidenstoff eingewebt wurden.',next:'Einen historischen Blumenstoff entdecken',done:'Deine Blume ist auf dem Stoff.',why:'So funktioniert der Druck',explain:'Die Farbe sitzt auf den erhöhten Teilen des Druckstocks. Beim Andrücken wird sie auf den Stoff übertragen. Du kannst denselben Stock immer wieder verwenden.',keys:'Mit der Tastatur: Tab zum Stoff, mit den Pfeiltasten die Stelle wählen und mit Enter drucken.',canvas:'Leerer Stoff zum Bedrucken',limit:'Dein Stoff hat schon 40 Motive. Im Atelier kannst du sie weiter bearbeiten.'},fr:{title:'Imprimez votre première fleur.',resume:'Continuez à imprimer votre tissu.',help:'Glissez la planche sur le tissu. Vous pouvez aussi toucher l’endroit où vous voulez poser la fleur.',ink:'Couleur',block:'Planche d’impression',context:'Les fleurs ornent les tissus depuis des siècles. Découvrez comment elles ont été tissées dans cette étoffe de soie.',next:'Découvrir une étoffe fleurie ancienne',done:'Voici votre empreinte.',why:'Comment ça marche ?',explain:'La couleur se trouve sur les parties en relief de la planche. Quand on appuie, elle passe sur le tissu. La même planche peut servir encore et encore.',keys:'Au clavier : utilisez Tab pour atteindre le tissu, les flèches pour choisir un endroit, puis Entrée pour imprimer.',canvas:'Tissu à imprimer',limit:'Votre tissu contient déjà 40 motifs. Vous pouvez les modifier dans l’atelier.'},en:{title:'Print your first flower.',resume:'Keep printing on your fabric.',help:'Drag the printing block onto the fabric. Or tap where you want your flower to go.',ink:'Print colour',block:'Printing block',context:'Flowers have decorated fabrics for centuries. Take a closer look at how they were woven into this silk.',next:'Explore a historic floral fabric',done:'Your flower is on the fabric.',why:'How does it work?',explain:'Colour sits on the raised parts of the block. Pressing the block transfers it to the fabric. The same block can be used again and again.',keys:'With a keyboard: Tab to the fabric, use the arrow keys to choose a spot, then press Enter to print.',canvas:'Fabric to print on',limit:'Your fabric already has 40 motifs. You can edit them in the studio.'}};
const routeWords={de:{preview:'Weiter: Stoff in Bewegung ansehen',hint:'Du kannst deinen Stoff jetzt ansehen und danach weitergestalten.',learn:'Kunst & Künstlerinnen entdecken (optional)'},fr:{preview:'Continuer : voir mon tissu en mouvement',hint:'Vous pouvez voir votre tissu maintenant et continuer à le créer ensuite.',learn:'Découvrir l’art et les créatrices (facultatif)'},en:{preview:'Continue: see my fabric in motion',hint:'See your fabric now. You can keep designing afterwards.',learn:'Explore the art and designers (optional)'}};
export function printingMarkup(locale,state,url,arrow){const t=words[locale],r=routeWords[locale],has=state.motifs?.length;return `<main id="main" class="hands-on-print scene-enter"><div class="print-introduction"><h1 tabindex="-1">${has?t.resume:t.title}</h1><p id="stamp-help">${t.help}</p></div><div class="printing-table"><div class="fabric-surface"><canvas id="stamp-fabric" width="600" height="600" tabindex="0" role="img" aria-label="${t.canvas}" aria-describedby="stamp-help stamp-keys"></canvas></div><aside class="block-rest"><button id="wood-block" aria-label="${t.block}" aria-describedby="stamp-help"><canvas width="220" height="250" aria-hidden="true"></canvas></button><span class="block-label">${t.block}</span><label>${t.ink}<select id="stamp-ink">${printCopy[locale].inkNames.map((n,i)=>`<option value="${i}" ${state.palette===i?'selected':''}>${n}</option>`).join('')}</select></label><details class="printing-reading"><summary>${t.why}</summary><p>${t.explain}</p><p id="stamp-keys">${t.keys}</p></details></aside></div><div class="stamp-complete"><p id="stamp-status" role="status"></p><p id="stamp-context" ${has?'':'hidden'}>${r.hint}</p><a class="story-primary" id="stamp-next" href="${url('souvenir')}" ${has?'':'hidden'}>${r.preview}${arrow}</a><a class="stamp-learn" id="stamp-learn" href="${url('regarder')}" ${has?'':'hidden'}>${r.learn}</a></div></main>`;}
export function bindPrinting(locale,state,save){const t=words[locale];if(!Array.isArray(state.motifs))state.motifs=[];const canvas=document.querySelector('#stamp-fabric'),ctx=canvas.getContext('2d'),block=document.querySelector('#wood-block'),blockCanvas=block.querySelector('canvas');let drag=null,ghost=null,focusPoint={x:.5,y:.4},keyboard=false;
 const draw=()=>{ctx.clearRect(0,0,600,600);ctx.drawImage(makeTile(state),0,0);ctx.save();ctx.lineWidth=.6;for(let n=0;n<600;n+=4){ctx.strokeStyle=n%8?'#64534509':'#ffffff22';ctx.beginPath();ctx.moveTo(n,0);ctx.lineTo(n,600);ctx.moveTo(0,n);ctx.lineTo(600,n);ctx.stroke()}ctx.restore();if(keyboard){ctx.strokeStyle='#173f3a';ctx.lineWidth=2;ctx.setLineDash([5,5]);ctx.strokeRect(focusPoint.x*600-50,focusPoint.y*600-50,100,130);ctx.setLineDash([])}};
 const paintBlock=()=>{const c=blockCanvas.getContext('2d');c.clearRect(0,0,220,250);c.fillStyle='#c59a6b';c.fillRect(0,0,220,250);c.strokeStyle='#805e3b';c.strokeRect(8,8,204,234);for(let y=25;y<240;y+=34){c.strokeStyle='#805e3b35';c.beginPath();c.moveTo(14,y);c.bezierCurveTo(70,y+8,150,y-6,205,y+2);c.stroke()}drawMotif(painterFor(c),{x:.5,y:.37,size:.25,angle:0,ink:state.palette,kind:0},220);};
 const point=e=>{const r=canvas.getBoundingClientRect();return {x:(e.clientX-r.left)/r.width,y:(e.clientY-r.top)/r.height}};
 const stamp=p=>{if(p.x<0||p.x>1||p.y<0||p.y>1)return;if(state.motifs.length>=40){document.querySelector('#stamp-status').textContent=t.limit;return}state.motifs.push({x:p.x,y:p.y,size:.14,angle:0,ink:state.palette,kind:0});state.bloom=true;state.edited=true;save();draw();document.querySelector('#stamp-status').textContent=t.done;document.querySelector('#stamp-next').hidden=false;document.querySelector('#stamp-context').hidden=false;document.querySelector('#stamp-learn').hidden=false;if(!state.paused)canvas.animate([{filter:'brightness(.96)'},{filter:'brightness(1)'}],{duration:250});};
 block.onpointerdown=e=>{if(e.button!==0)return;e.preventDefault();drag={id:e.pointerId,x:e.clientX,y:e.clientY,moved:false};block.setPointerCapture(e.pointerId);ghost=document.createElement('canvas');ghost.width=220;ghost.height=250;ghost.getContext('2d').drawImage(blockCanvas,0,0);ghost.className='stamp-ghost';ghost.style.width=canvas.getBoundingClientRect().width*.56+'px';ghost.style.left=e.clientX+'px';ghost.style.top=e.clientY+'px';document.body.append(ghost);block.classList.add('in-hand');};
 block.onpointermove=e=>{if(!drag||drag.id!==e.pointerId)return;drag.moved=drag.moved||Math.hypot(e.clientX-drag.x,e.clientY-drag.y)>5;ghost.style.left=e.clientX+'px';ghost.style.top=e.clientY+'px'};
 const release=e=>{if(!drag)return;const moved=drag.moved;drag=null;ghost?.remove();ghost=null;block.classList.remove('in-hand');if(block.hasPointerCapture(e.pointerId))block.releasePointerCapture(e.pointerId);if(e.type==='pointercancel')return;if(moved)stamp(point(e));else canvas.focus({preventScroll:true})};block.onpointerup=block.onpointercancel=release;
 block.onclick=e=>{if(e.detail===0){keyboard=true;canvas.focus();draw()}};
 canvas.onpointerdown=e=>{if(e.button!==0)return;keyboard=false;stamp(point(e))};canvas.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();keyboard=true;stamp(focusPoint)}else if(e.key.startsWith('Arrow')){e.preventDefault();keyboard=true;focusPoint.x=Math.max(.05,Math.min(.95,focusPoint.x+(e.key==='ArrowRight'?.05:e.key==='ArrowLeft'?-.05:0)));focusPoint.y=Math.max(.05,Math.min(.95,focusPoint.y+(e.key==='ArrowDown'?.05:e.key==='ArrowUp'?-.05:0)));draw()}};canvas.onblur=()=>{keyboard=false;draw()};document.querySelector('#stamp-ink').onchange=e=>{state.palette=Number(e.target.value);save();paintBlock()};paintBlock();draw();return {set(){draw()},destroy(){ghost?.remove();block.onpointerdown=block.onpointermove=block.onpointerup=block.onpointercancel=block.onclick=null;canvas.onpointerdown=canvas.onkeydown=canvas.onblur=null}};
}
