import {atelierMarkup,bindAtelier,atelierCopy} from './atelier.js?v=popova-and-patterns';
import {applyIdea} from './motif-model.js?v=popova-and-patterns';
import {Garden} from './garden.js?v=fresh-cloth-fit-screen';
import {printCopy} from './content.js?v=fresh-cloth-fit-screen';
import {copy} from './content.js?v=fresh-cloth-fit-screen';
import {journey} from './journey.js?v=popova-and-patterns';
import {Textile,downloadPattern} from './textile.js?v=popova-and-patterns';
export function stageMarkup(scene,phase,locale,state,url,arrow){
 const t=journey[locale],a=atelierCopy[locale];if(scene==='atelier')return atelierMarkup(locale,url,arrow);const action=(label,href)=>`<a class="stage-action" href="${href}">${label}${arrow}</a>`;
 const choices=()=>{if(Array.isArray(state.motifs))return `<dl class="design-summary"><div><dt>${a.summary}</dt><dd>${state.motifs.length} ${a.count}</dd></div><div><dt>${a.ground}</dt><dd>${a.grounds[state.ground]}</dd></div></dl>`;const values=[printCopy[locale].inkNames[state.palette],t.people[1].choices[state.ground],t.people[2].choices[state.layout],t.people[3].choices[state.scale]];return `<dl class="design-summary">${t.labels.map((label,i)=>`<div><dt>${label}</dt><dd>${values[i]}</dd></div>`).join('')}</dl>`;};
 if(scene==='decouverte')return `<main id="main" class="discovery-page scene-enter"><div class="discovery-flower"><canvas aria-hidden="true"></canvas></div><section class="discovery-intro"><h1 tabindex="-1">${t.discoverTitle}</h1><p class="end-lead">${t.discoverLead}</p><p>${t.thought}</p><div class="choice-row">${t.thoughtChoices.map((label,i)=>`<button data-thought="${i}" aria-pressed="${state.thought===i}">${label}</button>`).join('')}</div><p class="response" id="thought-response" aria-live="polite">${state.thought===null?'':t.thoughtReplies[state.thought]}</p>${action(t.discoverNext,url('fleur'))}</section><div class="stage-navigation"><a href="${url('jardin')}">${t.back}</a></div></main>`;
 if(scene==='tissu'||scene==='retour'){
 const returning=scene==='retour';const keys=['palette','ground','layout','scale'];const changed=state.beforeDesign&&keys.some(k=>state.beforeDesign[k]!==state[k]);
 return `<main id="main" class="cloth-page scene-enter"><div class="cloth-heading"><h1 tabindex="-1">${returning?t.returnTitle:t.clothTitle}</h1><p>${returning?t.returnLead:t.clothLead}</p></div><div class="flying-cloth"><canvas aria-hidden="true"></canvas><button class="zoom-button" id="zoom" aria-pressed="false">${t.zoom[0]} <span aria-hidden="true">+</span></button></div><div class="cloth-reading">${returning?`<h2>${t.choicesTitle}</h2>${choices()}<p>${state.edited?a.changed:changed?t.people[state.lastCreator].result:t.unchanged}</p>`:`<p>${t.clothText}</p><p class="interaction-hint">${t.clothHint}</p>`}</div><div class="open-atelier">${action(a.open,url('atelier'))}</div>${returning?'':`<section class="choose-invitation"><h2>${t.chooseTitle}</h2><p>${t.chooseLead}</p>${action(t.next,url('choix'))}</section>`}<div class="stage-navigation"><a href="${returning?url('creatrices',locale,state.lastCreator):url('fleur',locale,2)}">${t.back}</a>${returning?`<div class="return-actions"><a href="${url('choix')}">${t.another}</a>${action(t.take,url('souvenir'))}</div>`:''}</div></main>`;
 }
 if(scene==='choix')return `<main id="main" class="chooser-page scene-enter"><div class="chooser-heading"><h1 tabindex="-1">${t.chooseTitle}</h1><p>${t.chooseLead}</p></div><div class="recommended-path"><p>${t.recommendedText}</p><a href="${url('creatrices',locale,1)}">${t.suggest}${arrow}</a></div><div class="encounter-list">${t.people.map((p,i)=>`<a class="encounter encounter-${i}" href="${url('creatrices',locale,i)}"><div><h2>${p.name}</h2><p>${p.relation}</p></div><div><h3>${t.pick[i]}</h3><p>${t.pickDescription[i]}</p><span class="encounter-document">${t.objects[i]}</span></div><span class="encounter-go">${state.explored[i]?t.visited:t.visit}${arrow}</span></a>`).join('')}</div><div class="stage-navigation"><a href="${url('tissu')}">${t.back}</a><a href="${url('retour')}">${t.skip}</a></div></main>`;
 if(scene==='creatrices'){
 const p=t.people[phase];const selected=p.kind==='ink'?[5,2,6].indexOf(state.palette):state[p.kind];
 return `<main id="main" class="creator-page source-first creator-${phase} scene-enter"><div class="creator-return"><a href="${url('choix')}">${t.back}</a></div><div class="creator-layout"><article class="creator-copy"><h1 tabindex="-1">${p.name}</h1><p class="collection-relation">${p.relation}</p><h2>${p.title}</h2><p class="creator-body">${p.body}</p></article><figure class="source-document"><figcaption>${t.document}</figcaption><h2>${t.objects[phase]}</h2><p class="document-reading">${t.sourceNotes[phase]}</p><p class="excerpt-label">${t.excerpt}</p><p>${t.origins[phase]}</p><a href="${p.source}${phase===1?'#page=8':phase===2?'#page=2':''}" target="_blank" rel="noopener noreferrer">${t.readOriginal} ↗</a></figure></div><div class="encounter-bridge"><p>${t.connection[phase]}</p><button class="stage-action" id="try-design">${t.try}${arrow}</button></div><section class="experiment guided-experiment" id="experiment"><h2 tabindex="-1">${t.experimentTitle}</h2><div class="experiment-cloth"><canvas aria-hidden="true"></canvas></div><div class="experiment-controls"><h3>${p.task}</h3><div class="choice-row">${p.choices.map((label,i)=>`<button data-design="${i}" aria-pressed="${selected===i}">${label}</button>`).join('')}</div><p class="response" id="design-response" aria-live="polite">${state.explored[phase]?p.result:''}</p></div><p class="interpretation">${t.demo}</p></section><div class="stage-navigation"><a href="${url('choix')}">${t.another}</a>${action(t.returnAction,url('retour'))}</div></main>`;
 }
 return `<main id="main" class="souvenir-page scene-enter"><div class="souvenir-layout"><div class="souvenir-art"><canvas aria-hidden="true"></canvas><button class="zoom-button" id="zoom" aria-pressed="false">${t.zoom[0]} <span aria-hidden="true">+</span></button></div><section class="souvenir-copy"><h1 tabindex="-1">${t.endTitle}</h1><p class="end-lead">${t.endLead}</p><p>${t.learning}</p>${choices()}<details class="recall-optional"><summary>${t.quiz}</summary><fieldset class="recall"><legend class="sr-only">${t.quiz}</legend><div class="choice-row">${t.answers.map((s,i)=>`<button data-answer="${i}" aria-pressed="${state.answer===i}">${s}</button>`).join('')}</div><p class="response" id="answer-response" aria-live="polite">${state.answer===null?'':state.answer===0?t.correct:t.incorrect}</p></fieldset></details><a class="edit-again" href="${url('atelier')}">${a.open}</a><div class="downloads"><button class="stage-action" data-download="tile">${t.download}<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.4" aria-hidden="true"><path d="M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5"/></svg></button><button class="download-secondary" data-download="sheet">${t.downloadSheet}</button></div><p class="download-note">${t.downloadNote}</p><p role="status" id="download-status"></p><p class="original-note">${t.original}</p></section></div><p class="closing">${t.closing}</p><p class="independent">${copy[locale].independent}</p><details class="journey-sources"><summary>${t.sources}</summary><ul>${t.people.map(p=>`<li><a href="${p.source}" target="_blank" rel="noopener noreferrer">${p.name} — ${p.relation}</a></li>`).join('')}<li><a href="https://www.musee-impression.fr/exposition-temporaires-anterieures/" target="_blank" rel="noopener noreferrer">MISE — Quand les fleurs font l’étoffe, 2018–2020</a></li><li><a href="https://www.musee-impression.com/le-musee-de-limpression-sur-etoffes/" target="_blank" rel="noopener noreferrer">MISE — Impression à la planche</a></li><li><a href="https://www.moma.org/collection/artists/1480" target="_blank" rel="noopener noreferrer">MoMA — Sonia Delaunay</a></li></ul></details><div class="stage-navigation"><a href="${url('atelier')}">${t.back}</a><a href="${url('jardin')}">${t.restart}</a></div></main>`;
}
export function bindStage(scene,phase,locale,state,save){
 if(scene==='atelier')return bindAtelier(locale,state,save);
 const t=journey[locale];const canvas=document.querySelector('main canvas');const textile=scene==='decouverte'?new Garden(canvas,{scene:'decouverte',paused:state.paused}):canvas?new Textile(canvas,{design:state,paused:state.paused,flat:scene==='creatrices',reveal:scene==='souvenir'}):{set(){},destroy(){}};
 document.querySelector('#try-design')?.addEventListener('click',()=>{const section=document.querySelector('#experiment');section.scrollIntoView({behavior:state.paused?'instant':'smooth'});section.querySelector('h2').focus({preventScroll:true});});
 let zoom=false;document.querySelector('#zoom')?.addEventListener('click',e=>{zoom=!zoom;textile.set({zoom:zoom?1:0});e.currentTarget.setAttribute('aria-pressed',zoom);e.currentTarget.innerHTML=t.zoom[zoom?1:0]+` <span aria-hidden="true">${zoom?'−':'+'}</span>`;});
 document.querySelectorAll('[data-thought]').forEach(b=>b.addEventListener('click',()=>{state.thought=Number(b.dataset.thought);document.querySelectorAll('[data-thought]').forEach(x=>x.setAttribute('aria-pressed',x===b));document.querySelector('#thought-response').textContent=t.thoughtReplies[state.thought];save();}));
 document.querySelectorAll('[data-design]').forEach(b=>b.addEventListener('click',()=>{const p=t.people[phase],n=Number(b.dataset.design);applyIdea(state,p.kind,n);state.explored[phase]=true;document.querySelectorAll('[data-design]').forEach(x=>x.setAttribute('aria-pressed',x===b));textile.set({design:state});document.querySelector('#design-response').textContent=p.result;save();}));
 document.querySelectorAll('[data-answer]').forEach(b=>b.addEventListener('click',()=>{state.answer=Number(b.dataset.answer);document.querySelectorAll('[data-answer]').forEach(x=>x.setAttribute('aria-pressed',x===b));document.querySelector('#answer-response').textContent=state.answer===0?t.correct:t.incorrect;save();}));
 document.querySelectorAll('[data-download]').forEach(b=>b.addEventListener('click',async()=>{b.disabled=true;try{await downloadPattern(state,b.dataset.download==='sheet');document.querySelector('#download-status').textContent=t.downloadDone;}catch{document.querySelector('#download-status').textContent=t.downloadError;}finally{b.disabled=false;}}));
 return textile;
}
